# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/johanstr/code/phi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/johanstr/code/phi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/johanstr/code/phi/CMakeFiles /home/johanstr/code/phi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/johanstr/code/phi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named phi

# Build rule for target.
phi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phi
.PHONY : phi

# fast build rule for target.
phi/fast:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/build
.PHONY : phi/fast

src/barrier.o: src/barrier.cc.o

.PHONY : src/barrier.o

# target to build an object file
src/barrier.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/barrier.cc.o
.PHONY : src/barrier.cc.o

src/barrier.i: src/barrier.cc.i

.PHONY : src/barrier.i

# target to preprocess a source file
src/barrier.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/barrier.cc.i
.PHONY : src/barrier.cc.i

src/barrier.s: src/barrier.cc.s

.PHONY : src/barrier.s

# target to generate assembly for a file
src/barrier.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/barrier.cc.s
.PHONY : src/barrier.cc.s

src/blas_wrapper.o: src/blas_wrapper.cc.o

.PHONY : src/blas_wrapper.o

# target to build an object file
src/blas_wrapper.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/blas_wrapper.cc.o
.PHONY : src/blas_wrapper.cc.o

src/blas_wrapper.i: src/blas_wrapper.cc.i

.PHONY : src/blas_wrapper.i

# target to preprocess a source file
src/blas_wrapper.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/blas_wrapper.cc.i
.PHONY : src/blas_wrapper.cc.i

src/blas_wrapper.s: src/blas_wrapper.cc.s

.PHONY : src/blas_wrapper.s

# target to generate assembly for a file
src/blas_wrapper.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/blas_wrapper.cc.s
.PHONY : src/blas_wrapper.cc.s

src/complex_matrix.o: src/complex_matrix.cc.o

.PHONY : src/complex_matrix.o

# target to build an object file
src/complex_matrix.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/complex_matrix.cc.o
.PHONY : src/complex_matrix.cc.o

src/complex_matrix.i: src/complex_matrix.cc.i

.PHONY : src/complex_matrix.i

# target to preprocess a source file
src/complex_matrix.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/complex_matrix.cc.i
.PHONY : src/complex_matrix.cc.i

src/complex_matrix.s: src/complex_matrix.cc.s

.PHONY : src/complex_matrix.s

# target to generate assembly for a file
src/complex_matrix.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/complex_matrix.cc.s
.PHONY : src/complex_matrix.cc.s

src/cubic_spline.o: src/cubic_spline.cc.o

.PHONY : src/cubic_spline.o

# target to build an object file
src/cubic_spline.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/cubic_spline.cc.o
.PHONY : src/cubic_spline.cc.o

src/cubic_spline.i: src/cubic_spline.cc.i

.PHONY : src/cubic_spline.i

# target to preprocess a source file
src/cubic_spline.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/cubic_spline.cc.i
.PHONY : src/cubic_spline.cc.i

src/cubic_spline.s: src/cubic_spline.cc.s

.PHONY : src/cubic_spline.s

# target to generate assembly for a file
src/cubic_spline.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/cubic_spline.cc.s
.PHONY : src/cubic_spline.cc.s

src/hierarchy.o: src/hierarchy.cc.o

.PHONY : src/hierarchy.o

# target to build an object file
src/hierarchy.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy.cc.o
.PHONY : src/hierarchy.cc.o

src/hierarchy.i: src/hierarchy.cc.i

.PHONY : src/hierarchy.i

# target to preprocess a source file
src/hierarchy.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy.cc.i
.PHONY : src/hierarchy.cc.i

src/hierarchy.s: src/hierarchy.cc.s

.PHONY : src/hierarchy.s

# target to generate assembly for a file
src/hierarchy.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy.cc.s
.PHONY : src/hierarchy.cc.s

src/hierarchy_integrator.o: src/hierarchy_integrator.cc.o

.PHONY : src/hierarchy_integrator.o

# target to build an object file
src/hierarchy_integrator.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy_integrator.cc.o
.PHONY : src/hierarchy_integrator.cc.o

src/hierarchy_integrator.i: src/hierarchy_integrator.cc.i

.PHONY : src/hierarchy_integrator.i

# target to preprocess a source file
src/hierarchy_integrator.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy_integrator.cc.i
.PHONY : src/hierarchy_integrator.cc.i

src/hierarchy_integrator.s: src/hierarchy_integrator.cc.s

.PHONY : src/hierarchy_integrator.s

# target to generate assembly for a file
src/hierarchy_integrator.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy_integrator.cc.s
.PHONY : src/hierarchy_integrator.cc.s

src/hierarchy_node.o: src/hierarchy_node.cc.o

.PHONY : src/hierarchy_node.o

# target to build an object file
src/hierarchy_node.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy_node.cc.o
.PHONY : src/hierarchy_node.cc.o

src/hierarchy_node.i: src/hierarchy_node.cc.i

.PHONY : src/hierarchy_node.i

# target to preprocess a source file
src/hierarchy_node.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy_node.cc.i
.PHONY : src/hierarchy_node.cc.i

src/hierarchy_node.s: src/hierarchy_node.cc.s

.PHONY : src/hierarchy_node.s

# target to generate assembly for a file
src/hierarchy_node.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy_node.cc.s
.PHONY : src/hierarchy_node.cc.s

src/hierarchy_updater.o: src/hierarchy_updater.cc.o

.PHONY : src/hierarchy_updater.o

# target to build an object file
src/hierarchy_updater.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy_updater.cc.o
.PHONY : src/hierarchy_updater.cc.o

src/hierarchy_updater.i: src/hierarchy_updater.cc.i

.PHONY : src/hierarchy_updater.i

# target to preprocess a source file
src/hierarchy_updater.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy_updater.cc.i
.PHONY : src/hierarchy_updater.cc.i

src/hierarchy_updater.s: src/hierarchy_updater.cc.s

.PHONY : src/hierarchy_updater.s

# target to generate assembly for a file
src/hierarchy_updater.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hierarchy_updater.cc.s
.PHONY : src/hierarchy_updater.cc.s

src/hilbert_space_truncator.o: src/hilbert_space_truncator.cc.o

.PHONY : src/hilbert_space_truncator.o

# target to build an object file
src/hilbert_space_truncator.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hilbert_space_truncator.cc.o
.PHONY : src/hilbert_space_truncator.cc.o

src/hilbert_space_truncator.i: src/hilbert_space_truncator.cc.i

.PHONY : src/hilbert_space_truncator.i

# target to preprocess a source file
src/hilbert_space_truncator.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hilbert_space_truncator.cc.i
.PHONY : src/hilbert_space_truncator.cc.i

src/hilbert_space_truncator.s: src/hilbert_space_truncator.cc.s

.PHONY : src/hilbert_space_truncator.s

# target to generate assembly for a file
src/hilbert_space_truncator.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/hilbert_space_truncator.cc.s
.PHONY : src/hilbert_space_truncator.cc.s

src/parameter_input.o: src/parameter_input.cc.o

.PHONY : src/parameter_input.o

# target to build an object file
src/parameter_input.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/parameter_input.cc.o
.PHONY : src/parameter_input.cc.o

src/parameter_input.i: src/parameter_input.cc.i

.PHONY : src/parameter_input.i

# target to preprocess a source file
src/parameter_input.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/parameter_input.cc.i
.PHONY : src/parameter_input.cc.i

src/parameter_input.s: src/parameter_input.cc.s

.PHONY : src/parameter_input.s

# target to generate assembly for a file
src/parameter_input.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/parameter_input.cc.s
.PHONY : src/parameter_input.cc.s

src/phi.o: src/phi.cc.o

.PHONY : src/phi.o

# target to build an object file
src/phi.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/phi.cc.o
.PHONY : src/phi.cc.o

src/phi.i: src/phi.cc.i

.PHONY : src/phi.i

# target to preprocess a source file
src/phi.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/phi.cc.i
.PHONY : src/phi.cc.i

src/phi.s: src/phi.cc.s

.PHONY : src/phi.s

# target to generate assembly for a file
src/phi.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/phi.cc.s
.PHONY : src/phi.cc.s

src/phi_parameters.o: src/phi_parameters.cc.o

.PHONY : src/phi_parameters.o

# target to build an object file
src/phi_parameters.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/phi_parameters.cc.o
.PHONY : src/phi_parameters.cc.o

src/phi_parameters.i: src/phi_parameters.cc.i

.PHONY : src/phi_parameters.i

# target to preprocess a source file
src/phi_parameters.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/phi_parameters.cc.i
.PHONY : src/phi_parameters.cc.i

src/phi_parameters.s: src/phi_parameters.cc.s

.PHONY : src/phi_parameters.s

# target to generate assembly for a file
src/phi_parameters.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/phi_parameters.cc.s
.PHONY : src/phi_parameters.cc.s

src/restart_helper.o: src/restart_helper.cc.o

.PHONY : src/restart_helper.o

# target to build an object file
src/restart_helper.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/restart_helper.cc.o
.PHONY : src/restart_helper.cc.o

src/restart_helper.i: src/restart_helper.cc.i

.PHONY : src/restart_helper.i

# target to preprocess a source file
src/restart_helper.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/restart_helper.cc.i
.PHONY : src/restart_helper.cc.i

src/restart_helper.s: src/restart_helper.cc.s

.PHONY : src/restart_helper.s

# target to generate assembly for a file
src/restart_helper.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/restart_helper.cc.s
.PHONY : src/restart_helper.cc.s

src/timer.o: src/timer.cc.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cc.o:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/timer.cc.o
.PHONY : src/timer.cc.o

src/timer.i: src/timer.cc.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cc.i:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/timer.cc.i
.PHONY : src/timer.cc.i

src/timer.s: src/timer.cc.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cc.s:
	$(MAKE) -f CMakeFiles/phi.dir/build.make CMakeFiles/phi.dir/src/timer.cc.s
.PHONY : src/timer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... phi"
	@echo "... edit_cache"
	@echo "... src/barrier.o"
	@echo "... src/barrier.i"
	@echo "... src/barrier.s"
	@echo "... src/blas_wrapper.o"
	@echo "... src/blas_wrapper.i"
	@echo "... src/blas_wrapper.s"
	@echo "... src/complex_matrix.o"
	@echo "... src/complex_matrix.i"
	@echo "... src/complex_matrix.s"
	@echo "... src/cubic_spline.o"
	@echo "... src/cubic_spline.i"
	@echo "... src/cubic_spline.s"
	@echo "... src/hierarchy.o"
	@echo "... src/hierarchy.i"
	@echo "... src/hierarchy.s"
	@echo "... src/hierarchy_integrator.o"
	@echo "... src/hierarchy_integrator.i"
	@echo "... src/hierarchy_integrator.s"
	@echo "... src/hierarchy_node.o"
	@echo "... src/hierarchy_node.i"
	@echo "... src/hierarchy_node.s"
	@echo "... src/hierarchy_updater.o"
	@echo "... src/hierarchy_updater.i"
	@echo "... src/hierarchy_updater.s"
	@echo "... src/hilbert_space_truncator.o"
	@echo "... src/hilbert_space_truncator.i"
	@echo "... src/hilbert_space_truncator.s"
	@echo "... src/parameter_input.o"
	@echo "... src/parameter_input.i"
	@echo "... src/parameter_input.s"
	@echo "... src/phi.o"
	@echo "... src/phi.i"
	@echo "... src/phi.s"
	@echo "... src/phi_parameters.o"
	@echo "... src/phi_parameters.i"
	@echo "... src/phi_parameters.s"
	@echo "... src/restart_helper.o"
	@echo "... src/restart_helper.i"
	@echo "... src/restart_helper.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

